import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import calculationsRouter from "./calculations.js";
import indexesRouter from "./indexes.js";
import casesRouter from "./cases.js";
import criteriaRouter from "./criteria.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import statsRouter from "./stats.js";
import walletRouter from "./wallet.js";
import adminFinancialRouter from "./admin-financial.js";
import webhooksRouter from "./webhooks.js";
import previdenciarioSavesRouter from "./previdenciario-saves.js";
import plansRouter from "./plans.js";
import teamRouter from "./team.js";
import backupRouter from "./backup.js";
import taxTablesRouter from "./tax-tables.js";
import supportRouter from "./support.js";
import ferramentasRouter from "./ferramentas.js";
import controladoriaRouter from "./controladoria.js";
import conveniosRouter from "./convenios.js";
import tjmgRouter from "./tjmg.js";
import civilSavesRouter from "./civil-saves.js";
import adminCuponsRouter from "./admin-cupons.js";
import accessLogsRouter from "./access-logs.js";
const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/stats", statsRouter);
router.use("/wallet", walletRouter);
router.use("/admin/financial", adminFinancialRouter);
router.use("/calculations", calculationsRouter);
router.use("/indexes", indexesRouter);
router.use("/cases", casesRouter);
router.use("/criteria", criteriaRouter);
router.use("/webhooks", webhooksRouter);
router.use("/previdenciario", previdenciarioSavesRouter);
router.use("/plans", plansRouter);
router.use("/team", teamRouter);
router.use("/backup", backupRouter);
router.use("/tax-tables", taxTablesRouter);
router.use("/support", supportRouter);
router.use("/ferramentas", ferramentasRouter);
router.use("/controladoria", controladoriaRouter);
router.use("/convenios", conveniosRouter);
router.use("/tjmg", tjmgRouter);
router.use("/civil", civilSavesRouter);
router.use("/admin/cupons", adminCuponsRouter);
router.use("/access-logs", accessLogsRouter);

export default router;
